theme:
  name: material
  highlightjs: true
  logo: /img/abcdesktop.svg
  favicon: /img/abcdesktop128x128.ico
  hljs_languages:
    - bash
    - yaml
    - javascript
    - python
  features:
    - navigation.top
    - navigation.tabs
    - content.action.edit
    - content.code.copy
plugins:
    - search
    - tags
extra:
  abcdesktop:
    latest_release: !ENV [ABCDESKTOP_LATEST_RELEASE, '4.4']
  analytics:
    provider: google
    property: G-TN9YC7J01Z
markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
site_name: abcdesktop.pepins.net
repo_url: https://github.com/abcdesktopio/newdocs
repo_name: abcdesktopio/newdocs
site_url: https://abcdesktop.pepins.net
edit_uri: 'edit/main/opsdocs/docs'
nav:
- Home: index.md
- Requirements : requirements.md
- Quick Start :
  - Install :
    - Bash script: install/4.4/bash.md
    - Helm: install/4.4/helm.md
  - Install Applications:
    - Overview:  install/4.4/applicationoverview.md
    - List all apps:  install/4.4/listallapplication.md
    - Console : install/4.4/applicationwithconsole.md
  - Uninstall : install/4.4/uninstall.md
- Advanced :
  - Platform Cloud:
    - AWS :
      - Install on Amazon AWS with Elastic Kubernetes Service: cloudproviders/4.4/aws/aws.md
      - Expose using a load balancer: cloudproviders/4.4/aws/aws-loadbalancer.md
      - Expose using a nginx ingress controller: cloudproviders/4.4/aws/aws-nginx-ingress-controller.md
    - AZURE :
      - Install on Microsoft AZURE Kubernetes service: cloudproviders/4.4/azure/azure.md
      - Expose using a load balancer: cloudproviders/4.4/azure/azure-loadbalancer.md
      - Expose using a nginx ingress controller: cloudproviders/4.4/azure/azure-nginx-ingress-controller.md
    - Digital Ocean :
      - Install on Digital Ocean Kubernetes cluster: cloudproviders/4.4/digitalocean/digitalocean.md
      - Expose using a load balancer: cloudproviders/4.4/digitalocean/digitalocean-loadbalancer.md
      - Expose using a nginx ingress controller: cloudproviders/4.4/digitalocean/digitalocean-nginx-ingress-controller.md
    - GCP :
      - Install on Google GCP Kubernetes cluster : cloudproviders/4.4/gcp/gcp.md
      - Expose using a load balancer: cloudproviders/4.4/gcp/gcp-loadbalancer.md
      - Expose using a GKE ingress controller: cloudproviders/4.4/gcp/gcp-gke-ingress-controller.md
    - OVH :
      - Install on OVHcloud Kubernetes cluster : cloudproviders/4.4/ovh/ovh.md
      - Expose using a load balancer: cloudproviders/4.4/ovh/ovh-loadbalancer.md
      - Expose using a nginx ingress controller: cloudproviders/4.4/ovh/ovh-nginx-ingress-controller.md
  - Platform On-Premises:
    - Kind: advanced/4.4/install/onpremises/kind.md
    - Kubernetes: advanced/4.4/install/onpremises/kubernetes.md
    - MiniKube: advanced/4.4/install/onpremises/minikube.md
  - Install Applications:
    - Create your own application: advanced/4.4/createyourownapplication.md
  - Network Policy:
    - Netpol: advanced/4.4/networkpolicy/netpol.md
    - Install : advanced/4.4/networkpolicy/install.md
    - Uninstall: advanced/4.4/networkpolicy/uninstall.md
  - Storage:
    - PV: advanced/4.4/storage/pv.md
    - PVC: advanced/4.4/storage/pvc.md
    - HostPath: advanced/4.4/storage/hostpath.md
    - Shared Volume: advanced/4.4/storage/sharedvolume.md
  - Rules and labels:
    - Rules: advanced/4.4/rulesandlabels/rules.md
    - Labels:  advanced/4.4/rulesandlabels/labels.md
  - Authentication :
    - OAuth: advanced/4.4/authentication/oauth.md
    - LDAP: advanced/4.4/authentication/ldap.md
    - Anonymous: advanced/4.4/authentication/anonymous.md
- Contribute :
  - Overview: contribute/overview.md
  - Services:
    - Mongo: contribute/4.4/services/mongo.md
    - Console: contribute/4.4/services/console.md
    - Pyos: contribute/4.4/services/pyos.md
    - Router: contribute/4.4/services/router.md
    - WebModules: contribute/4.4/services/webmodules.md
  - User Pod:
    - Graphical: contribute/4.4/userpod/graphical.md
    - Sound: contribute/4.4/userpod/sound.md
    - Cups: contribute/4.4/userpod/cups.md
    - Filer: contribute/4.4/userpod/filer.md
- FAQ: faq.md
