# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: dispatch-from-oc.app
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone sources
        run: |
          rm -rf ..?* .[!.]* *
          git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" clone "https://github.com/abcdesktopio/docs.git" .
          git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" submodule update --init --recursive --remote
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name : install material
        run: pip install mkdocs-material
      
      - name: Run Makefile
        run: make docs
        
      - name: push data to pages
        run: |
           git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" clone "https://github.com/abcdesktopio/abcdesktopio.github.io.git"
           echo 'ls -la opsdocs/site'
           ls -la opsdocs/site
           cp -r opsdocs/site/* abcdesktopio.github.io
           cp CNAME abcdesktopio.github.io
           cp LICENSE abcdesktopio.github.io
           cd abcdesktopio.github.io
           git add *
           git commit -m 'pushed from abcdesktopio/docs' -a
           git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" push
           
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.docs
          event-type: dispatch-from-docs
