# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: dispatch-from-oc.template
    
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          
      - name: dump-github-event-client_payload
        run: |
          echo "client_payload.repository ${{ github.event.client_payload.repository }}"
          echo "client_payload.run_id ${{ github.event.client_payload.run_id }}"
          echo "client_payload.artifact ${{ github.event.client_payload.artifact }}"
          echo "client_payload.filename is ${{ github.event.client_payload.filename }}"
          
      - name: get artifact 
        run: |
          gh run download ${{ github.event.client_payload.run_id }} -n ${{ github.event.client_payload.artifact }} --repo abcdesktopio/oc.template
          ls -la 
          
      
