# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
permissions:
  contents: write

env: 
  # ABCDESKTOP_LATEST_RELEASE: ${{ vars.ABCDESKTOP_LATEST_RELEASE }}
  ABCDESKTOP_LATEST_RELEASE: '4.4'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name : install material
        run: make install
      
      - name: Run Makefile
        run: make docs
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: opsdocs/site # The folder the action should deploy.
